"""add_agent_pending_action_table

Revision ID: 5ae0d73c1013
Revises: 20260311_0010_add_schedule_frequency
Create Date: 2026-03-12 01:32:59.424095
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ae0d73c1013'
down_revision = '20260311_0010_add_schedule_frequency'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_pending_actions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('conversation_id', sa.String(length=36), nullable=True),
    sa.Column('tool_name', sa.String(length=128), nullable=False),
    sa.Column('tool_args', sa.JSON(), nullable=False),
    sa.Column('tool_call_id', sa.String(length=64), nullable=True),
    sa.Column('conversation_state', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('paper_id', sa.String(length=36), nullable=True),
    sa.Column('markdown', sa.Text(), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['agent_conversations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['paper_id'], ['papers.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_pending_actions_conversation_id'), 'agent_pending_actions', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_agent_pending_actions_paper_id'), 'agent_pending_actions', ['paper_id'], unique=False)
    op.drop_index(op.f('ix_ieee_quotas_date'), table_name='ieee_api_quotas')
    op.drop_index(op.f('ix_ieee_quotas_topic_id'), table_name='ieee_api_quotas')
    op.drop_table('ieee_api_quotas')
    op.alter_column('action_papers', 'id',
               existing_type=sa.VARCHAR(length=36),
               nullable=False)
    op.create_unique_constraint('uq_action_paper', 'action_papers', ['action_id', 'paper_id'])
    op.drop_constraint(None, 'action_papers', type_='foreignkey')
    op.drop_constraint(None, 'action_papers', type_='foreignkey')
    op.create_foreign_key(None, 'action_papers', 'collection_actions', ['action_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'action_papers', 'papers', ['paper_id'], ['id'], ondelete='CASCADE')
    op.alter_column('agent_conversations', 'user_id',
               existing_type=sa.VARCHAR(length=256),
               type_=sa.String(length=36),
               existing_nullable=True)
    op.alter_column('agent_conversations', 'title',
               existing_type=sa.VARCHAR(length=512),
               type_=sa.String(length=256),
               existing_nullable=True)
    op.create_index(op.f('ix_agent_conversations_created_at'), 'agent_conversations', ['created_at'], unique=False)
    op.alter_column('agent_messages', 'role',
               existing_type=sa.VARCHAR(length=32),
               type_=sa.String(length=20),
               existing_nullable=False)
    op.create_index(op.f('ix_agent_messages_created_at'), 'agent_messages', ['created_at'], unique=False)
    op.drop_column('agent_messages', 'metadata_json')
    op.drop_column('agent_messages', 'markdown')
    op.drop_column('agent_messages', 'paper_id')
    op.alter_column('collection_actions', 'id',
               existing_type=sa.VARCHAR(length=36),
               nullable=False)
    op.alter_column('collection_actions', 'action_type',
               existing_type=sa.VARCHAR(length=32),
               type_=sa.Enum('initial_import', 'manual_collect', 'auto_collect', 'agent_collect', 'subscription_ingest', 'reference_import', name='action_type'),
               existing_nullable=False)
    op.drop_index(op.f('ix_collection_actions_created_at'), table_name='collection_actions')
    op.drop_index(op.f('ix_collection_actions_type'), table_name='collection_actions')
    op.create_index(op.f('ix_collection_actions_action_type'), 'collection_actions', ['action_type'], unique=False)
    op.drop_constraint(None, 'collection_actions', type_='foreignkey')
    op.create_foreign_key(None, 'collection_actions', 'topic_subscriptions', ['topic_id'], ['id'], ondelete='SET NULL')
    op.alter_column('generated_contents', 'metadata_json',
               existing_type=sqlite.JSON(),
               nullable=True)
    op.alter_column('image_analyses', 'id',
               existing_type=sa.VARCHAR(length=36),
               nullable=False)
    op.drop_constraint(None, 'image_analyses', type_='foreignkey')
    op.create_foreign_key(None, 'image_analyses', 'papers', ['paper_id'], ['id'], ondelete='CASCADE')
    op.alter_column('papers', 'read_status',
               existing_type=sa.VARCHAR(length=8),
               type_=sa.Enum('unread', 'skimmed', 'deep_read', name='read_status'),
               existing_nullable=False,
               existing_server_default=sa.text("'Unread'"))
    op.drop_index(op.f('ix_papers_doi'), table_name='papers')
    op.drop_index(op.f('ix_papers_source'), table_name='papers')
    op.drop_index(op.f('ix_papers_source_id'), table_name='papers')
    op.drop_column('papers', 'source_id')
    op.drop_column('papers', 'doi')
    op.drop_column('papers', 'source')
    op.drop_index(op.f('ix_pipeline_runs_created_at'), table_name='pipeline_runs')
    op.drop_index(op.f('ix_prompt_traces_created_at'), table_name='prompt_traces')
    op.alter_column('topic_subscriptions', 'schedule_frequency',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=32),
               existing_nullable=False,
               existing_server_default=sa.text("'daily'"))
    op.drop_column('topic_subscriptions', 'ieee_api_key_override')
    op.drop_column('topic_subscriptions', 'sources')
    op.drop_column('topic_subscriptions', 'ieee_daily_quota')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('topic_subscriptions', sa.Column('ieee_daily_quota', sa.INTEGER(), server_default=sa.text("'10'"), nullable=False))
    op.add_column('topic_subscriptions', sa.Column('sources', sqlite.JSON(), server_default=sa.text('\'["arxiv"]\''), nullable=False))
    op.add_column('topic_subscriptions', sa.Column('ieee_api_key_override', sa.VARCHAR(length=512), nullable=True))
    op.alter_column('topic_subscriptions', 'schedule_frequency',
               existing_type=sa.String(length=32),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False,
               existing_server_default=sa.text("'daily'"))
    op.create_index(op.f('ix_prompt_traces_created_at'), 'prompt_traces', ['created_at'], unique=False)
    op.create_index(op.f('ix_pipeline_runs_created_at'), 'pipeline_runs', ['created_at'], unique=False)
    op.add_column('papers', sa.Column('source', sa.VARCHAR(length=32), server_default=sa.text("'arxiv'"), nullable=False))
    op.add_column('papers', sa.Column('doi', sa.VARCHAR(length=128), nullable=True))
    op.add_column('papers', sa.Column('source_id', sa.VARCHAR(length=128), nullable=True))
    op.create_index(op.f('ix_papers_source_id'), 'papers', ['source_id'], unique=False)
    op.create_index(op.f('ix_papers_source'), 'papers', ['source'], unique=False)
    op.create_index(op.f('ix_papers_doi'), 'papers', ['doi'], unique=False)
    op.alter_column('papers', 'read_status',
               existing_type=sa.Enum('unread', 'skimmed', 'deep_read', name='read_status'),
               type_=sa.VARCHAR(length=8),
               existing_nullable=False,
               existing_server_default=sa.text("'Unread'"))
    op.drop_constraint(None, 'image_analyses', type_='foreignkey')
    op.create_foreign_key(None, 'image_analyses', 'papers', ['paper_id'], ['id'])
    op.alter_column('image_analyses', 'id',
               existing_type=sa.VARCHAR(length=36),
               nullable=True)
    op.alter_column('generated_contents', 'metadata_json',
               existing_type=sqlite.JSON(),
               nullable=False)
    op.drop_constraint(None, 'collection_actions', type_='foreignkey')
    op.create_foreign_key(None, 'collection_actions', 'topic_subscriptions', ['topic_id'], ['id'])
    op.drop_index(op.f('ix_collection_actions_action_type'), table_name='collection_actions')
    op.create_index(op.f('ix_collection_actions_type'), 'collection_actions', ['action_type'], unique=False)
    op.create_index(op.f('ix_collection_actions_created_at'), 'collection_actions', ['created_at'], unique=False)
    op.alter_column('collection_actions', 'action_type',
               existing_type=sa.Enum('initial_import', 'manual_collect', 'auto_collect', 'agent_collect', 'subscription_ingest', 'reference_import', name='action_type'),
               type_=sa.VARCHAR(length=32),
               existing_nullable=False)
    op.alter_column('collection_actions', 'id',
               existing_type=sa.VARCHAR(length=36),
               nullable=True)
    op.add_column('agent_messages', sa.Column('paper_id', sa.VARCHAR(length=36), nullable=True))
    op.add_column('agent_messages', sa.Column('markdown', sa.TEXT(), server_default=sa.text("('')"), nullable=False))
    op.add_column('agent_messages', sa.Column('metadata_json', sqlite.JSON(), server_default=sa.text("'{}'"), nullable=False))
    op.drop_index(op.f('ix_agent_messages_created_at'), table_name='agent_messages')
    op.alter_column('agent_messages', 'role',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=32),
               existing_nullable=False)
    op.drop_index(op.f('ix_agent_conversations_created_at'), table_name='agent_conversations')
    op.alter_column('agent_conversations', 'title',
               existing_type=sa.String(length=256),
               type_=sa.VARCHAR(length=512),
               existing_nullable=True)
    op.alter_column('agent_conversations', 'user_id',
               existing_type=sa.String(length=36),
               type_=sa.VARCHAR(length=256),
               existing_nullable=True)
    op.drop_constraint(None, 'action_papers', type_='foreignkey')
    op.drop_constraint(None, 'action_papers', type_='foreignkey')
    op.create_foreign_key(None, 'action_papers', 'papers', ['paper_id'], ['id'])
    op.create_foreign_key(None, 'action_papers', 'collection_actions', ['action_id'], ['id'])
    op.drop_constraint('uq_action_paper', 'action_papers', type_='unique')
    op.alter_column('action_papers', 'id',
               existing_type=sa.VARCHAR(length=36),
               nullable=True)
    op.create_table('ieee_api_quotas',
    sa.Column('id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('topic_id', sa.VARCHAR(length=36), nullable=True),
    sa.Column('date', sa.DATE(), nullable=False),
    sa.Column('api_calls_used', sa.INTEGER(), nullable=False),
    sa.Column('api_calls_limit', sa.INTEGER(), nullable=False),
    sa.Column('last_reset_at', sa.DATETIME(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['topic_id'], ['topic_subscriptions.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('topic_id', 'date', name=op.f('uq_ieee_quota_daily'))
    )
    op.create_index(op.f('ix_ieee_quotas_topic_id'), 'ieee_api_quotas', ['topic_id'], unique=False)
    op.create_index(op.f('ix_ieee_quotas_date'), 'ieee_api_quotas', ['date'], unique=False)
    op.drop_index(op.f('ix_agent_pending_actions_paper_id'), table_name='agent_pending_actions')
    op.drop_index(op.f('ix_agent_pending_actions_conversation_id'), table_name='agent_pending_actions')
    op.drop_table('agent_pending_actions')
    # ### end Alembic commands ###
